/* Liste pentru autocomplete la checkout (județ / localitate / țară).
   Localitatea permite și text liber (pentru comune/sate care nu sunt în listă). */

export const JUDETE = [
  "Alba", "Arad", "Argeș", "Bacău", "Bihor", "Bistrița-Năsăud", "Botoșani",
  "Brașov", "Brăila", "București", "Buzău", "Caraș-Severin", "Călărași", "Cluj",
  "Constanța", "Covasna", "Dâmbovița", "Dolj", "Galați", "Giurgiu", "Gorj",
  "Harghita", "Hunedoara", "Ialomița", "Iași", "Ilfov", "Maramureș", "Mehedinți",
  "Mureș", "Neamț", "Olt", "Prahova", "Satu Mare", "Sălaj", "Sibiu", "Suceava",
  "Teleorman", "Timiș", "Tulcea", "Vaslui", "Vâlcea", "Vrancea",
];

export const TARI = [
  "România", "Republica Moldova",
  "Albania", "Austria", "Belarus", "Belgia", "Bosnia și Herțegovina", "Bulgaria",
  "Cehia", "Cipru", "Croația", "Danemarca", "Elveția", "Estonia", "Finlanda",
  "Franța", "Germania", "Grecia", "Irlanda", "Islanda", "Italia", "Kosovo",
  "Letonia", "Lituania", "Luxemburg", "Macedonia de Nord", "Malta", "Marea Britanie",
  "Muntenegru", "Norvegia", "Olanda", "Polonia", "Portugalia", "Rusia", "Serbia",
  "Slovacia", "Slovenia", "Spania", "Suedia", "Turcia", "Ucraina", "Ungaria",
  "Statele Unite ale Americii", "Canada", "Australia", "Noua Zeelandă",
  "Japonia", "China", "Coreea de Sud", "India", "Emiratele Arabe Unite", "Israel",
  "Egipt", "Maroc", "Africa de Sud", "Brazilia", "Argentina", "Mexic",
];

export const LOCALITATI = [
  // reședințe de județ + municipii + orașe mari
  "București", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov",
  "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Pitești", "Sibiu", "Bacău",
  "Târgu Mureș", "Baia Mare", "Buzău", "Botoșani", "Satu Mare", "Râmnicu Vâlcea",
  "Drobeta-Turnu Severin", "Suceava", "Piatra Neamț", "Focșani", "Târgoviște",
  "Bistrița", "Reșița", "Tulcea", "Slatina", "Călărași", "Alba Iulia", "Giurgiu",
  "Deva", "Hunedoara", "Zalău", "Sfântu Gheorghe", "Bârlad", "Vaslui", "Roman",
  "Turda", "Media", "Slobozia", "Alexandria", "Voluntari", "Lugoj", "Medgidia",
  "Onești", "Miercurea Ciuc", "Sighetu Marmației", "Petroșani", "Mangalia",
  "Tecuci", "Odorheiu Secuiesc", "Râmnicu Sărat", "Pașcani", "Dej", "Reghin",
  "Năvodari", "Câmpina", "Mediaș", "Fetești", "Săcele", "Câmpulung", "Caracal",
  "Sighișoara", "Făgăraș", "Fălticeni", "Curtea de Argeș", "Sebeș", "Huși",
  "Aiud", "Câmpia Turzii", "Carei", "Blaj", "Lupeni", "Vulcan", "Rădăuți",
  "Gherla", "Motru", "Petrila", "Comănești", "Moinești", "Câmpulung Moldovenesc",
  "Vatra Dornei", "Gheorgheni", "Toplița", "Cugir", "Orăștie", "Zărnești",
  "Codlea", "Râșnov", "Buftea", "Otopeni", "Popești-Leordeni", "Pantelimon",
  "Bragadiru", "Chitila", "Măgurele", "Chiajna", "Mioveni", "Costești", "Băicoi",
  "Breaza", "Sinaia", "Bușteni", "Azuga", "Comarnic", "Vălenii de Munte",
  "Urziceni", "Oltenița", "Roșiori de Vede", "Turnu Măgurele", "Zimnicea",
  "Videle", "Bolintin-Vale", "Corabia", "Balș", "Drăgășani", "Băile Olănești",
  "Călimănești", "Horezu", "Băbeni", "Mărășești", "Adjud", "Panciu", "Odobești",
  "Găești", "Moreni", "Pucioasa", "Fieni", "Titu", "Târgu Jiu", "Rovinari",
  "Bumbești-Jiu", "Novaci", "Târnăveni", "Luduș", "Sovata", "Sighetu Marmației",
  "Vișeu de Sus", "Borșa", "Târgu Lăpuș", "Seini", "Cavnic", "Negrești-Oaș",
  "Tășnad", "Șimleu Silvaniei", "Jibou", "Cehu Silvaniei", "Beclean", "Năsăud",
  "Sângeorz-Băi", "Dorohoi", "Săveni", "Darabani", "Flămânzi", "Ștefănești",
  "Hârlău", "Târgu Frumos", "Podu Iloaiei", "Negrești", "Murgeni", "Berești",
  "Târgu Bujor", "Ianca", "Însurăței", "Nehoiu", "Pogoanele", "Pătârlagele",
  "Cernavodă", "Murfatlar", "Eforie", "Techirghiol", "Ovidiu", "Hârșova",
  "Băneasa", "Negru Vodă", "Isaccea", "Babadag", "Măcin", "Sulina",
  "Vânju Mare", "Strehaia", "Baia de Aramă", "Orșova", "Filiași", "Băilești",
  "Calafat", "Dăbuleni", "Segarcea", "Bechet", "Sânnicolau Mare", "Jimbolia",
  "Buziaș", "Deta", "Făget", "Recaș", "Gătaia", "Ciacova", "Ineu", "Lipova",
  "Chișineu-Criș", "Curtici", "Pâncota", "Nădlac", "Sântana", "Pecica",
  "Beiuș", "Marghita", "Salonta", "Aleșd", "Ștei", "Valea lui Mihai", "Săcueni",
  "Cisnădie", "Avrig", "Tălmaciu", "Agnita", "Dumbrăveni", "Copșa Mică", "Ocna Sibiului",
  "Vișeu", "Târgu Neamț", "Bicaz", "Roznov", "Băile Herculane", "Anina", "Oravița",
  "Bocșa", "Caransebeș", "Moldova Nouă", "Oțelu Roșu",
];
